Vagrant.configure("2") do |config|
    config.vm.define "k8s-master" do |cfg|
      cfg.vm.box = "generic/ubuntu2004"
        cfg.vm.provider "virtualbox" do |vbox|
        vbox.name = "k8s-master"
            vbox.cpus = 4
            vbox.memory = 16384
        end
        cfg.vm.host_name = "k8s-master"
        cfg.vm.network "private_network", ip: "192.168.56.161"
        cfg.vm.network "forwarded_port", guest: 22, host: "30021", auto_correct: true, id: "ssh", host_ip:"0.0.0.0"
        cfg.vm.synced_folder ".", "/vagrant", disabled: true
        cfg.vm.provision "shell", path: "ssh.sh"
        cfg.vm.provision "shell", path: "crio.sh"
        cfg.vm.provision "shell", path: "k8s.sh"
        cfg.vm.provision "shell", path: "k8s-m.sh"
      end
    (2..4).each do |i|
        config.vm.define "k8s-worker#{i-1}" do |cfg|
          cfg.vm.box = "generic/ubuntu2004"
            cfg.vm.provider "virtualbox" do |vbox|
            vbox.name = "k8s-worker#{i-1}"
                vbox.cpus = 4
                vbox.memory = 327668
            end
            cfg.vm.host_name = "k8s-worker#{i-1}"
            cfg.vm.network "private_network", ip: "192.168.56.16#{i}"
            cfg.vm.network "forwarded_port", guest: 22, host: "3002#{i}", auto_correct: true, id: "ssh", host_ip:"0.0.0.0"
            cfg.vm.synced_folder ".", "/vagrant", disabled: true
            cfg.vm.provision "shell", path: "ssh.sh"
            cfg.vm.provision "shell", path: "crio.sh"
            cfg.vm.provision "shell", path: "k8s.sh"
            cfg.vm.provision "shell", path: "k8s-w.sh"
          end
      end
    end