- name: install control node
  hosts: control
  remote_user:  "admin" 
  become: True
  gather_facts: True
  vars_files: vars/main.yaml
  roles:
    - { role: ./role/control }

- name: install Linux packages files
  hosts: k8s-cluster
  remote_user:  "admin" 
  become: True
  gather_facts: True
  vars_files: vars/main.yaml
  roles:
    - { role: ./role/nodes }

- name: install rke2-cluster-master-init
  hosts: masters-init
  remote_user:  "admin" 
  become: True
  gather_facts: True
  vars_files: vars/main.yaml
  roles:
    - { role: ./role/masters-init }

- name: install rke2-cluster-master-connect
  hosts: masters-connect
  remote_user:  "admin" 
  become: True
  gather_facts: True
  vars_files: vars/main.yaml
  roles:
    - { role: ./role/masters-connect}

- name: install rke2-cluster-workers
  hosts: workers
  remote_user:  "admin" 
  become: True
  gather_facts: True
  vars_files: vars/main.yaml
  roles:
    - { role: ./role/workers }

- name: install apps
  hosts: masters-init
  remote_user:  "admin" 
  become: True
  gather_facts: True
  vars_files: vars/main.yaml
  roles:
    - { role: ./role/deploy_app }
