- name: install rke2-cluster-master-connect
  hosts: masters-connect
  remote_user: "{{ USER }}"
  become: True
  gather_facts: True
  vars_files: vars/main.yaml
  roles:
    - { role: ./role/masters-connect}