- name: kubeadm init
  shell: kubeadm init \
    --control-plane-endpoint={{ BASTION_NODE_IP }}:6443 \
    --pod-network-cidr=10.244.0.0/16 \
    --upload-certs \
    --kubernetes-version v1.28.2
    --token-ttl 0 | grep -A 2 "kubeadm join" 
  register: INIT_COMMAND
  tags:
    - k8s_init

- name: Remove "\\n\\t" from the registered output
  set_fact:
    CLEAN_OUT: "{{ INIT_COMMAND.stdout | regex_replace('\\\\n\\\\t', '') }}"
  tags:
    - k8s_init

- name: debugging
  debug:
    msg: "{{ CLEAN_OUT }}"
  tags:
    - k8s_init

- name: create file
  file:
    path: '/tmp/JOIN_COMMAND'
    state: touch
  tags:
    - k8s_init

- name: Save registered output to a file
  blockinfile:
    path: '/tmp/JOIN_COMMAND'
    block: |
      {{ CLEAN_OUT }}
  tags:
    - k8s_init

- name: Save registered output to a file -Master
  shell: 'cat "/tmp/JOIN_COMMAND" | head -n 4 > "/tmp/JOIN_COMMAND_M"'
  tags:
    - k8s_init

- name: Save registered output to a file -Worker
  shell: 'cat "/tmp/JOIN_COMMAND" | tail -n 3 > "/tmp/JOIN_COMMAND_W"'
  tags:
    - k8s_init

- name: fetching file -Master
  fetch:
    src: "/tmp/JOIN_COMMAND_M" 
    dest: "/tmp/JOIN_COMMAND_M"
    flat: yes
  tags:
    - k8s_init

- name: fetching file -Worker
  fetch:
    src: "/tmp/JOIN_COMMAND_W" 
    dest: "/tmp/JOIN_COMMAND_W"
    flat: yes
  tags:
    - k8s_init

- name: create directory
  file:
    path: '/root/.kube/'
    state: directory  
  tags:
    - k8s_init

- name: kubeadm init - debug
  debug:
    msg: "{{ INIT_COMMAND }}"
  tags:
    - k8s_init

- name: copy resource
  copy:
    src: "k8s_yaml"
    dest: "/root/"
  tags:
    - k8s_init

- name: extract tools
  unarchive:
    src: 'k8s_yaml/helm-v3.13.3-linux-amd64.tar.gz'
    dest: '/root/k8s_yaml/'
  tags:
    - k8s_init

- name: mv helm
  copy: 
    src: '/root/k8s_yaml/linux-amd64/helm'
    dest: '/usr/local/bin/helm'
    remote_src: yes
  tags:
    - k8s_init

- name: set Kubeconfig
  blockinfile:
    path: '/etc/bash.bashrc'
  #    path: '/root/.bashrc'
    block: |
      export KUBECONFIG=/etc/kubernetes/admin.conf
      alias k=kubectl
  #    complete -o default -F __start_kubectl k 
  #  copy: 
  #    src: '/etc/kubernetes/admin.conf'
  #    dest: '/root/.kube/config.yaml'
  #    remote_src: yes
  tags:
    - k8s_init

- name: source bashrc
  shell: . /root/.bashrc
  ignore_errors: yes
  tags:
    - k8s_init

- name: deploy CNI
  shell: kubectl apply -f /root/k8s_yaml/kube-flannel.yaml --kubeconfig=/etc/kubernetes/admin.conf
  tags:
    - k8s_init
    - redo
