---
# tasks file for rke2-cluster
- name: install rpm for control nodes
  include_tasks: rpm_install_control.yaml
  tags:
    - control
    - nginx-rpm
    - docker-rpm


- name: install control resource
  include_tasks: control.yaml
  tags:
    - control
    - nginx-setting
    - docker
    - nexus
    - gitea
    - kube
