# - name: 0-1-3. rpm Install nginx
#   shell: "rpm -Uvh {{ item }}"
#   with_items:
#     - "{{ LOCAL_PATH.PACKAGES }}/nginx/libXpm-3.5.12-11.el8.x86_64.rpm"
#     - "{{ LOCAL_PATH.PACKAGES }}/nginx/libwebp-1.0.0-9.el8.x86_64.rpm"
#     - "{{ LOCAL_PATH.PACKAGES }}/nginx/gd-2.2.5-6.el8.x86_64.rpm"
#     - "{{ LOCAL_PATH.PACKAGES }}/nginx/libxslt-1.1.32-6.el8.x86_64.rpm"
#     - "{{ LOCAL_PATH.PACKAGES }}/nginx/openssl3-libs-3.0.7-5.el8.1.x86_64.rpm"
#     - "{{ LOCAL_PATH.PACKAGES }}/nginx/centos-logos-httpd-85.8-2.el8.noarch.rpm"
#     - "{{ LOCAL_PATH.PACKAGES }}/nginx/nginx-filesystem-1.23.1-2.module_el8+15017+873f21d4.noarch.rpm"
#     - "{{ LOCAL_PATH.PACKAGES }}/nginx/nginx-core-1.23.1-2.module_el8+15017+873f21d4.x86_64.rpm"
#     - "{{ LOCAL_PATH.PACKAGES }}/nginx/nginx-1.23.1-2.module_el8+15017+873f21d4.x86_64.rpm"
#     - "{{ LOCAL_PATH.PACKAGES }}/nginx/nginx-mod-stream-1.23.1-2.module_el8+15017+873f21d4.x86_64.rpm"
#   tags:
#     - control
#     - nginx-install


#  shell: "yum install -y {{ LOCAL_PATH.PACKAGES }}/nginx/*.rpm"

- name: 0-1-1. rpm Install nginx
  shell: "rpm -Uvh {{ item }}"
  with_items:
    - "{{ LOCAL_PATH.PACKAGES }}/nginx/libX11-common-1.6.8-7.el8.noarch.rpm"
    - "{{ LOCAL_PATH.PACKAGES }}/nginx/libXau-1.0.9-3.el8.x86_64.rpm"
    - "{{ LOCAL_PATH.PACKAGES }}/nginx/libxcb-1.13.1-1.el8.x86_64.rpm"
    - "{{ LOCAL_PATH.PACKAGES }}/nginx/libX11-1.6.8-7.el8.x86_64.rpm"
    - "{{ LOCAL_PATH.PACKAGES }}/nginx/libXpm-3.5.12-11.el8.x86_64.rpm"
    - "{{ LOCAL_PATH.PACKAGES }}/nginx/libwebp-1.0.0-9.el8.x86_64.rpm"
    - "{{ LOCAL_PATH.PACKAGES }}/nginx/fontconfig-2.13.1-4.el8.x86_64.rpm"
    - "{{ LOCAL_PATH.PACKAGES }}/nginx/libjpeg-turbo-1.5.3-12.el8.x86_64.rpm"
    - "{{ LOCAL_PATH.PACKAGES }}/nginx/jbigkit-libs-2.1-14.el8.x86_64.rpm"
    - "{{ LOCAL_PATH.PACKAGES }}/nginx/libtiff-4.0.9-31.el8.x86_64.rpm"
    - "{{ LOCAL_PATH.PACKAGES }}/nginx/gd-2.2.5-6.el8.x86_64.rpm"
    - "{{ LOCAL_PATH.PACKAGES }}/nginx/libxslt-1.1.32-6.el8.x86_64.rpm"
    - "{{ LOCAL_PATH.PACKAGES }}/nginx/openssl3-libs-3.0.7-5.el8.1.x86_64.rpm"
    - "{{ LOCAL_PATH.PACKAGES }}/nginx/centos-logos-httpd-85.8-2.el8.noarch.rpm"
    - "{{ LOCAL_PATH.PACKAGES }}/nginx/nginx-filesystem-1.23.1-2.module_el8+15017+873f21d4.noarch.rpm"
    - "{{ LOCAL_PATH.PACKAGES }}/nginx/nginx-core-1.23.1-2.module_el8+15017+873f21d4.x86_64.rpm"
    - "{{ LOCAL_PATH.PACKAGES }}/nginx/nginx-1.23.1-2.module_el8+15017+873f21d4.x86_64.rpm"
    - "{{ LOCAL_PATH.PACKAGES }}/nginx/nginx-mod-stream-1.23.1-2.module_el8+15017+873f21d4.x86_64.rpm"
  ignore_errors: True
  tags:
    - control
    - nginx-rpm

- name: 0-1-2. Install rpm to Docker
  shell: "rpm -Uvh {{ LOCAL_PATH.PACKAGES }}/docker/repotrack/{{ item }}"
  with_items:
    - grub2-common-2.02-148.el8_8.1.rocky.0.3.noarch.rpm --nodeps
    - grub2-tools-2.02-148.el8_8.1.rocky.0.3.x86_64.rpm --nodeps
    - grub2-tools-minimal-2.02-148.el8_8.1.rocky.0.3.x86_64.rpm --nodeps
    - ncurses-6.1-9.20180224.el8_8.1.x86_64.rpm --nodeps
    - ncurses-base-6.1-9.20180224.el8_8.1.noarch.rpm --nodeps
    - ncurses-libs-6.1-9.20180224.el8_8.1.x86_64.rpm --nodeps
    - glib2-2.56.4-161.el8.x86_64.rpm --nodeps
    - glibc-2.28-225.el8_8.6.x86_64.rpm --nodeps
    - glibc-all-langpacks-2.28-225.el8_8.6.x86_64.rpm --nodeps
    - glibc-common-2.28-225.el8_8.6.x86_64.rpm --nodeps
    - glibc-gconv-extra-2.28-225.el8_8.6.x86_64.rpm --nodeps
    - iptables-1.8.4-24.el8_8.2.x86_64.rpm --nodeps
    - iptables-libs-1.8.4-24.el8_8.2.x86_64.rpm --nodeps
    - policycoreutils-2.9-24.el8.x86_64.rpm
    - policycoreutils-python-utils-2.9-24.el8.noarch.rpm
    - container-selinux-2.205.0-2.module+el8.8.0+1265+fa25dd7a.noarch.rpm
    - containerd.io-1.6.24-3.1.el8.x86_64.rpm
    - fuse3-libs-3.3.0-16.el8.x86_64.rpm
    - fuse-common-3.3.0-16.el8.x86_64.rpm
    - fuse3-3.3.0-16.el8.x86_64.rpm
    - fuse-overlayfs-1.11-1.module+el8.8.0+1265+fa25dd7a.x86_64.rpm
    - libslirp-4.4.0-1.module+el8.8.0+1265+fa25dd7a.x86_64.rpm
    - slirp4netns-1.2.0-2.module+el8.8.0+1265+fa25dd7a.x86_64.rpm
    - libcgroup-0.41-19.el8.x86_64.rpm
    - docker-buildx-plugin-0.11.2-1.el8.x86_64.rpm
    - docker-ce-rootless-extras-24.0.6-1.el8.x86_64.rpm --nodeps
    - docker-ce-24.0.6-1.el8.x86_64.rpm --nodeps
    - docker-ce-cli-24.0.6-1.el8.x86_64.rpm --nodeps
    - docker-compose-plugin-2.21.0-1.el8.x86_64.rpm
  ignore_errors: True
  tags:
    - control
    - docker-rpm


