#!/usr/bin/bash

images=(
    "registry.k8s.io/kube-apiserver:v1.28.2"
    "registry.k8s.io/kube-controller-manager:v1.28.2"
    "registry.k8s.io/kube-scheduler:v1.28.2"
    "registry.k8s.io/kube-proxy:v1.28.2"
    "registry.k8s.io/pause:3.9"
    "registry.k8s.io/etcd:3.5.9-0"
    "registry.k8s.io/coredns/coredns:v1.10.1"
)

for image in "${images[@]}"; do
    # Pull the image from the registry
    docker pull "{{ REGISTRY_URL }}:{{ REGISTRY_PORT }}/$image"
    docker tag "{{ REGISTRY_URL }}:{{ REGISTRY_PORT }}/$image" $image

    # Save the image to a tar file on the local disk
    image_name=$(echo "$image" | sed 's|/|_|g' | sed 's/:/_/g')
    docker save -o "${image_name}.tar" "$image"
    ctr -n k8s.io images import ${image_name}.tar
done