---
# tasks file for container-runtimes
- name: copy resource
  copy:
    src: "{{ dist_type }}/runc.tar"
    dest: "/{{ install_dir }}/"
    mode: 0644
  tags:
    - crio

- name: unarchive runc.tar
  unarchive:
    src: "/{{ install_dir }}/runc.tar"
    dest: "/{{ install_dir }}/"
    remote_src: yes
  tags:
    - crio

- name: Index *.deb file
  find:
    path: "/{{ install_dir }}/{{ item }}"
    file_type: file
    patterns: "*.deb"
  with_items:
    - 1_apt_update
    - 2_apt_crio
  register: deb_array
  tags:
    - crio

- name: dpkg configure
  shell: "dpkg --configure -a"
  tags:
    - crio

- name: install Deb files
  apt:
    deb: "{{ item }}"
    state: present
  with_items:
    - "{{ deb_array.files | map(attribute='path') | list }}"
  tags:
    - crio

- name: crio enable & start
  systemd:
    name: crio
    state: started
    enabled: yes
  tags:
    - crio
