- name: get command
  copy: 
    src: '/tmp/JOIN_COMMAND_W'
    dest: '/tmp/JOIN_COMMAND_W'
  tags:
    - k8s_worker

- name: kubeadm connect
  shell: '. /tmp/JOIN_COMMAND_W' 
  register: INIT_COMMAND
  tags:
    - k8s_worker

- name: kubeadm init - debug
  debug:
    msg: "{{ INIT_COMMAND }}"
  tags:
    - k8s_worker

- name: copy resource
  copy:
    src: "k8s_yaml"
    dest: "/root/"
  tags:
    - k8s_worker