- name: install control node
  hosts: control
  become: True
  gather_facts: True
  vars_files: vars/main.yaml
  roles:
    - { role: ./role/control }
---
- name: install Linux packages files
  hosts: all
  become: True
  gather_facts: True
  vars_files: vars/main.yaml
  roles:
    - { role: ./role/nodes }
---
- name: install rke2-cluster-master-init
  hosts: masters-init
  become: True
  gather_facts: True
  vars_files: vars/main.yaml
  roles:
    - { role: ./role/masters-init }
---
- name: install rke2-cluster-master-connect
  hosts: masters-connect
  become: True
  gather_facts: True
  vars_files: vars/main.yaml
  roles:
    - { role: ./role/masters-connect}
---
- name: install rke2-cluster-workers
  hosts: workers
  become: True
  gather_facts: True
  vars_files: vars/main.yaml
  roles:
    - { role: ./role/workers }
---
- name: install apps
  hosts: masters-init
  become: True
  gather_facts: True
  vars_files: vars/main.yaml
  roles:
    - { role: ./role/deploy_app }