---
# tasks file for container-runtimes
- name: copy resource
  copy:
    src: "{{ dist_type }}/runc.tar"
    dest: "{{ install_dir }}/"
    mode: 0644
  tags:
    - crio
    - redo

- name: unarchive runc.tar
  unarchive:
    src: "{{ install_dir }}/runc.tar"
    dest: "{{ install_dir }}/"
    remote_src: yes
  tags:
    - crio
    - redo

- name: Index *.deb file
  find:
    path: "{{ install_dir }}/2_apt_crio"
    file_type: file
    patterns: "*.deb"
  register: deb_array_2
  tags:
    - crio
    - redo

- name: dpkg configure
  shell: "dpkg --configure -a"
  tags:
    - crio
    - redo

- name: install Deb files
  shell: "dpkg -i {{ install_dir }}/2_apt_crio/*.deb" 
  #  apt:
  #    deb: "{{ item }}"
  #    state: present
  #  with_items:
  #    - "{{ deb_array_2.files | map(attribute='path') | list }}"
  tags:
    - crio
    - redo

- name: crio enable & start
  systemd:
    name: crio
    state: started
    enabled: yes
  tags:
    - crio
    - redo

- name: crio.conf
  shell: sed -i -e 's|# insecure_registries = \[|insecure_registries = [\n  "192.168.56.1:5443"\n]|g' /etc/crio/crio.conf
  tags:
    - crio
    - redo

- name: crio process restart
  systemd:
    name: crio
    state: restarted
  tags:
    - crio
    - redo
