---
# tasks file for container-runtimes
- name: copy resource
  copy:
    src: "{{ dist_type }}/base.tar"
    dest: "{{ install_dir }}/"
    mode: 0644
  tags:
    - crio
    - redo

- name: unarchive base.tar
  unarchive:
    src: "{{ install_dir }}/base.tar"
    dest: "{{ install_dir }}/"
    remote_src: yes
  tags:
    - crio
    - redo

- name: Index *.deb file
  find:
    path: "{{ install_dir }}/2_update_docker"
    file_type: file
    patterns: "*.deb"
  register: deb_array_2
  tags:
    - crio
    - redo

- name: dpkg configure
  shell: "dpkg --configure -a"
  tags:
    - crio
    - redo

- name: install Deb files
  shell: "dpkg -i {{ install_dir }}/2_update_docker/*.deb" 
  #  apt:
  #    deb: "{{ item }}"
  #    state: present
  #  with_items:
  #    - "{{ deb_array_2.files | map(attribute='path') | list }}"
  tags:
    - crio
    - redo

- name: crio enable & start
  systemd:
    name: crio
    state: started
    enabled: yes
  tags:
    - crio
    - redo
