---
# tasks file for container-runtimes
- name: copy resource
  copy:
    src: "{{ item }}"
    dest: "{{ LOCAL_PATH.BASE }}/"
    mode: 0644
  with_items: 
    - "{{ dist_type }}/2_update_docker"
    - "{{ dist_type }}/3_k8s_tools"
    - cni-plugins-linux-amd64-v1.3.0.tgz
    - crictl-v1.27.0-linux-amd64.tar.gz
  tags:
    - docker

- name: mkdir 
  file:
    path: "/opt/cni/bin"
    state: directory
  tags:
    - docker

- name: unarchive base.tar
  unarchive:
    src: "{{ LOCAL_PATH.BASE }}/{{ item.src}}"
    dest: "{{ item.dest }}"
    remote_src: yes
  with_items: 
    - { src: "cni-plugins-linux-amd64-v1.3.0.tgz", dest: "/opt/cni/bin"}
    - { src: "crictl-v1.27.0-linux-amd64.tar.gz", dest: "/usr/local/bin"}
  tags:
    - docker

- name: Index *.deb file
  find:
    path: "{{ LOCAL_PATH.BASE }}/2_update_docker"
    file_type: file
    patterns: "*.deb"
  register: deb_array_2
  when: dist_type == "ubuntu"
  tags:
    - docker

- name: dpkg configure
  shell: "dpkg --configure -a"
  when: dist_type == "ubuntu"
  tags:
    - docker

- name: install Deb files
  shell: "dpkg -i {{ LOCAL_PATH.BASE }}/2_update_docker/*.deb" 
  when: dist_type == "ubuntu"
  tags:
    - docker

- name: install Rpm files
  shell: "yum install -y {{ LOCAL_PATH.BASE }}/2_update_docker/*.rpm" 
  when: "{{ dist_type }} == 'rpm_files'"
  tags:
    - docker

- name: docker enable & start
  systemd:
    name: docker
    state: started
    enabled: yes
  tags:
    - docker

- name: docker daemon.json
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
  tags:
    - docker
    - redo

- name: docker restart
  systemd:
    name: docker
    state: restarted
    enabled: yes
  tags:
    - docker
    - redo

- name: docker login 
  shell: printf "admin1234\n" | docker login {{ REGISTRY_URL }}:{{ REGISTRY_PORT }} --username admin --password-stdin
  tags:
    - docker
    - redo