---
# tasks file for container-runtimes
- name: copy resource
  copy:
    src: "{{ dist_type }}/base.tar"
    dest: "{{ install_dir }}/"
    mode: 0644
  tags:
    - docker
    - redo

- name: unarchive base.tar
  unarchive:
    src: "{{ install_dir }}/base.tar"
    dest: "{{ install_dir }}/"
    remote_src: yes
  tags:
    - docker
    - redo

- name: Index *.deb file
  find:
    path: "{{ install_dir }}/2_update_docker"
    file_type: file
    patterns: "*.deb"
  register: deb_array_2
  tags:
    - docker
    - redo

- name: dpkg configure
  shell: "dpkg --configure -a"
  tags:
    - docker
    - redo

- name: install Deb files
  shell: "dpkg -i {{ install_dir }}/2_update_docker/*.deb" 
  #  apt:
  #    deb: "{{ item }}"
  #    state: present
  #  with_items:
  #    - "{{ deb_array_2.files | map(attribute='path') | list }}"
  tags:
    - docker
    - redo

- name: docker enable & start
  systemd:
    name: docker
    state: started
    enabled: yes
  tags:
    - docker
    - redo

- name: docker daemon.json
  file:
    path: /etc/docker/daemon.json
    state: touch
  tags:
    - docker
    - redo

- name: docker daemon.json
  blockinfile:
    path: /etc/docker/daemon.json
    block: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "insecure-registries" : ["localhost:5000"],
        "allow-nondistributable-artifacts": ["localhost:5000"],
        "log-driver": "json-file",
        "log-opts": {
                "max-size": "100m"
        },
        "group": "rnd",
        "storage-driver": "overlay2",
        "storage-opts": [
                "overlay2.override_kernel_check=true"
        ]
      }
  tags:
    - docker
    - redo