---
# tasks file for container-runtimes
- name: dpkg configure
  shell: "dpkg --configure -a"
  tags:
    - k8s_tools

- name: Install *.deb files
  shell: printf "Y\n" | dpkg -i /tmp/3_k8s_tools/*.deb
  tags:
    - k8s_tools

- name: docker login
  shell: docker login {{ CONTROL_REGISTRY }} --username admin --password admin1234
  tags:
    - k8s_tools 

- name: kube-completion step
  shell: |
    kubectl completion bash | sudo tee /etc/bash_completion.d/kubectl > /dev/null
    echo 'alias k=kubectl' >>~/.bashrc
    echo 'complete -o default -F __start_kubectl k' >>~/.bashrc
  tags:
    - k8s_tools

- name: copy crictl.yaml
  copy:
   src: config/crictl.yaml
   dest: /etc/crictl.yaml
   mode: 0644
  tags:
    - k8s_tools

- name: daemo-reload
  shell: systemctl daemon-reload
  tags:
    - k8s_tools
  
- name: resetard systemd
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items: 
    - containerd
    - kubelet
  tags:
    - k8s_tools

- name: run registry
  shell: docker run -d -p 5000:5000 --restart=always --name registry {{ CONTROL_REGISTRY }}/registry:2.8.2
  tags:
    - k8s_tools
    - registry

- name: copy image_saves
  template:
   src: images_pull
   dest: /root/images_pull
   mode: 0755
  tags:
    - k8s_tools
    - registry

- name : run image_saves
  shell: /root/images_pull
  tags:
    - k8s_tools
    - registry


# - name: pull calico
#   shell: "docker pull {{ CONTROL_REGISTRY }}/{{ item }}"
#   with_items: 
#     - calico/cni:v3.26.1
#     - calico/node:v3.26.1
#     - calico/kube-controllers:v3.26.1
#   when: K8S_CNI == "calico"
#   tags:
#     - k8s_tools
#     - registry

# - name: tagging config
#   shell: "docker tag {{ CONTROL_REGISTRY }}/{{ item }} localhost:5000/{{ item }}"
#   with_items: 
#     - calico/cni:v3.26.1
#     - calico/node:v3.26.1
#     - calico/kube-controllers:v3.26.1
#   when: K8S_CNI == "calico"
#   tags:
#     - k8s_tools
#     - registry

# - name: push config to localhost
#   shell: "docker push localhost:5000/{{ item }}"
#   with_items: 
#     - calico/cni:v3.26.1
#     - calico/node:v3.26.1
#     - calico/kube-controllers:v3.26.1
#   when: K8S_CNI == "calico"
#   tags:
#     - k8s_tools
#     - registry

# - name: pull flannel
#   shell: "docker pull {{ CONTROL_REGISTRY }}/flannel/{{ item }}"
#   with_items: 
#     - flannel:v0.22.0
#     - flannel-cni-plugin:v1.1.2
#   when: K8S_CNI == "flannel"
#   tags:
#     - k8s_tools
#     - registry

# - name: tagging config
#   shell: "docker tag {{ CONTROL_REGISTRY }}/{{ item }} localhost:5000/{{ item }}"
#   with_items: 
#     - flannel/flannel:v0.22.0
#     - flannel/flannel-cni-plugin:v1.1.2
#   when: K8S_CNI == "flannel"
#   tags:
#     - k8s_tools
#     - registry

# - name: push config to localhost
#   shell: "docker push localhost:5000/{{ item }}"
#   with_items: 
#     - flannel/flannel:v0.22.0
#     - flannel/flannel-cni-plugin:v1.1.2
#   when: K8S_CNI == "flannel"
#   tags:
#     - k8s_tools
#     - registry