---
# tasks file for container-runtimes

- name: swap off
  shell: swapoff -a
  tags:
    - k8s_base

- name: net.ipv4.ip_forward=1
  shell: sysctl -w net.ipv4.ip_forward=1
  tags:
    - k8s_base

- name: rewrite fstab
  shell: sed -i '/swap/s/^/#/' /etc/fstab
  tags:
    - k8s_base

- name: modprobe br_netfilter
  shell: 'modprobe br_netfilter'
  tags:
    - k8s_base

- name: sysctl net bridge
  shell: sysctl -w net.bridge.bridge-nf-call-iptables=1
  tags:
    - k8s_base

- name: disble Firewalld
  shell: ufw disable
  tags:
    - k8s_base

- name: disable systemd-resolved
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no
  tags:
    - k8s_base

- name: Cofigure DNS default
  shell: sed -i '/\[main\]/a dns=default' /etc/NetworkManager/NetworkManager.conf
  tags:
    - k8s_base

- name: unlink resolv.conf
  shell: unlink /etc/resolv.conf || true
  tags:
    - k8s_base

- name: touch resolv.conf
  file:
    path: /etc/resolv.conf
    state: touch
  tags:
    - k8s_base

- name: set-hostname
  hostname:
    name: "{{ inventory_hostname }}"
  tags:
    - k8s_base

- name: copy /etc/hosts
  copy:
    src: /etc/hosts
    dest: /etc/hosts
  tags:
    - k8s_base

- name: copy /etc/resolv.conf
  copy:
    src: /etc/resolv.conf
    dest: /etc/resolv.conf
  tags:
    - k8s_base
