---
# tasks file for container-runtimes

- name: write 99-k8s-cri.conf
  shell: |
    cat > /etc/sysctl.d/99-k8s-cri.conf << EOF
    net.bridge.bridge-nf-call-iptables=1
    net.ipv4.ip_forward=1
    net.bridge.bridge-nf-call-ip6tables=1
    EOF
  tags:
    - k8s_base

- name: write k8s.conf
  shell: 'echo -e overlay\\nbr_netfilter > /etc/modules-load.d/k8s.conf'
  tags:
    - k8s_base

- name: swap memory step_1
  file: 
    path: /etc/systemd/zram-generator.conf
    state: touch
  tags:
    - k8s_base

- name: mask systemd-zram-setup.service
  shell: systemctl mask systemd-zram-setup@.service
  tags:
    - k8s_base

- name: rewrite fstab
  shell: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
  tags:
    - k8s_base

- name: disble Firewalld
  shell: ufw disable
  tags:
    - k8s_base

- name: disable systemd-resolved
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no
  tags:
    - k8s_base

- name: Cofigure DNS default
  shell: sed -i '/\[main\]/a dns=default' /etc/NetworkManager/NetworkManager.conf
  tags:
    - k8s_base

- name: unlink resolv.conf
  shell: unlink /etc/resolv.conf || true
  tags:
    - k8s_base

- name: touch resolv.conf
  file:
    path: /etc/resolv.conf
    state: touch
  tags:
    - k8s_base

- name: set-hostname
  hostname:
    name: "{{ inventory_hostname }}"
  tags:
    - k8s_base

- name: copy /etc/hosts
  copy:
    src: /etc/hosts
    dest: /etc/hosts
  tags:
    - k8s_base

