---
# tasks file for container-runtimes
- name: copy host file
  copy:
    src: /etc/hosts
    dest: /etc/hosts
  tags:
    - k8s_base
  
- name: swap off
  shell: swapoff -a
  tags:
    - k8s_base

- name: rewrite fstab
  shell: sed -i '/swap/s/^/#/' /etc/fstab
  tags:
    - k8s_base

- name: net.ipv4.ip_forward=1
  shell: | 
    tee /etc/modules-load.d/containerd.conf <<EOF
    overlay
    br_netfilter
    EOF
  tags:
    - k8s_base



- name: modprobe br_netfilter
  shell: "modprobe {{ item }}"
  with_items: 
    - br_netfilter
    - overlay
  tags:
    - k8s_base

- name: sysctl net bridge
  shell: |
    tee /etc/sysctl.d/kube.conf <<EOT
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-iptables = 1
    net.ipv4.ip_forward = 1
    EOT
  tags:
    - k8s_base

- name: apply sysctl
  shell: sysctl --system
  tags:
    - k8s_base
  
- name: configure cgroup
  shell: |
    containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1
    sudo sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml

- name: containerd restart
  systemd:
    name: containerd
    state: restarted
    enabled: yes
  tags:
    - k8s_base

- name: disble Firewalld
  shell: ufw disable
  tags:
    - k8s_base

- name: Cofigure DNS default
  shell: sed -i '/\[main\]/a dns=default' /etc/NetworkManager/NetworkManager.conf
  tags:
    - k8s_base

- name: unlink resolv.conf
  shell: unlink /etc/resolv.conf || true
  tags:
    - k8s_base

- name: touch resolv.conf
  file:
    path: /etc/resolv.conf
    state: touch
  tags:
    - k8s_base

- name: mkdir kubelet service_d
  file:
    path: /etc/systemd/system/kubelet.service.d/
    state: directory
  tags:
    - k8s_base

- name: Copy kubelet serviced
  copy:
    src: images/kubelet.service
    dest: /etc/systemd/system/kubelet.service
  tags:
    - k8s_base

- name: Copy 10-kubeamd.conf
  copy:
    src: images/10-kubeadm.conf
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  tags: 
    - k8s_base

- name: copy config.toml
  copy:
    src: images/config.toml
    dest: /etc/containerd/config.toml
  tags:
    - k8s_base

- name: touch debug.toml
  file:
    path: /etc/containerd/debug.toml
    state: touch
  tags:
    - k8s_base

- name: set-hostname
  hostname:
    name: "{{ inventory_hostname }}"
  tags:
    - k8s_base

- name: set default ipv4
  shell: "ip route default via {{ ansible_enp0s8.ipv4.address }}"
  tags:
    - k8s_base

- name: copy /etc/resolv.conf
  copy:
    src: /etc/resolv.conf
    dest: /etc/resolv.conf
  tags:
    - k8s_base
    - images
