---
# tasks file for container-runtimes
- name: install runc
  include_tasks: crio.yml
  tags: 
    - crio
    - redo
- name: configure Node
  include_tasks: k8s_base.yml  
  tags: 
    - k8s_base

- name: install kube-tools
  include_tasks: k8s_tools.yml  
  tags: 
    - k8s_tools

