---
# tasks file for container-runtimes
- name: install docker
  include_tasks: docker.yml

- name: configure Node
  include_tasks: k8s_base.yml  

- name: install kube-tools
  include_tasks: k8s_tools.yml  
