- name: 5-3-1. create check script 1
  file:
    path: /root/check.sh
    state: touch
    mode: 0755
  tags:
    - check_maria
    - wait_maria
    
- name: 5-3-2. create check script 2
  blockinfile:
    path: /root/check.sh
    block: |
      animation="|/-\\"
      echo -e "\e[32mCreating MariaDB Pod: $(date +%H:%M:%S)\e[0m"
      MARIADB_SVC_IP=$(/var/lib/rancher/rke2/bin/kubectl get svc mariadb -n db | awk '/mariadb/ {print $3}')
      while true; do
        MARIADB_POD_STATUS=$(/var/lib/rancher/rke2/bin/kubectl get pod -n db mariadb-primary-0 -o=jsonpath='{.status.conditions[1].status}' 2>/dev/null)
        for i in $(seq 0 3); do
          echo -e -n "${animation:$i:1}"
          sleep {{ DELAY }}
          echo -e -en "\b"
        done

        if [ "$MARIADB_POD_STATUS" == "True" ]; then
          MARIADB_SVC_STATUS=$(mysqladmin -u root -p{{ MARIADB_ROOT_PASSWORD }} ping -h $MARIADB_SVC_IP 2>/dev/null)
          if [ "$MARIADB_SVC_STATUS" == "mysqld is alive" ]; then
            echo -e "\e[32mSuccess for Creating MariaDB Pod\e[0m"
            break
          fi
          sleep 2
        else
          CURRENT_TIME=$(date +%s)
          ELAPSED_TIME=$((CURRENT_TIME - {{ START_TIME }}))

          # TimeOut: Error To Create MariaDB Pod
          if [ $ELAPSED_TIME -ge {{ TIMEOUT }} ]; then
            echo -e "\e[31mTimeOut: Error To Create MariaDB Pod: $(date +%H:%M:%S)\e[0m"
            exit 1
          fi
        fi
      done
  tags:
    - check_maria
    - wait_maria

- name: 5-3-3. running check script
  shell: /root/check.sh
  tags:
    - check_maria
    - wait_maria        

- name: 5-3-4. Get SVC ip
  shell: /var/lib/rancher/rke2/bin/kubectl get svc mariadb -n db | awk '/mariadb/ {print $3}'
  register: MARIADB_SVC_IP
  tags:
    - check_maria
    - cleanup_db

# 하기 tasks들에서 문제가 발생할 경우, 사용가능한 cleaninig script
- name: 5-3-5. create cleanup_db script 1
  file:
    path: /root/cleanup_db.sh
    state: touch
    mode: 0755
  tags:
    - check_maria
    - cleanup_db

- name: 5-3-6. create cleanup_db script 2
  blockinfile:
    path: /root/cleanup_db.sh
    block: |
      mysql -u root -p{{ MARIADB_ROOT_PASSWORD }} -h {{ MARIADB_SVC_IP.stdout }} -e "DROP DATABASE IF EXISTS master;" --init-command="SET SESSION FOREIGN_KEY_CHECKS=0"
      mysql -u root -p{{ MARIADB_ROOT_PASSWORD }} -h {{ MARIADB_SVC_IP.stdout }} -e "DROP DATABASE IF EXISTS master_smp;" --init-command="SET SESSION FOREIGN_KEY_CHECKS=0"
      mysql -u root -p{{ MARIADB_ROOT_PASSWORD }} -h {{ MARIADB_SVC_IP.stdout }} -e "DROP DATABASE IF EXISTS tts_master;" --init-command="SET SESSION FOREIGN_KEY_CHECKS=0"
      mysql -u root -p{{ MARIADB_ROOT_PASSWORD }} -h {{ MARIADB_SVC_IP.stdout }} -e "DROP DATABASE IF EXISTS stt_master;" --init-command="SET SESSION FOREIGN_KEY_CHECKS=0"
      mysql -u root -p{{ MARIADB_ROOT_PASSWORD }} -h {{ MARIADB_SVC_IP.stdout }} -e "DROP DATABASE IF EXISTS chub_cms;" --init-command="SET SESSION FOREIGN_KEY_CHECKS=0"
      mysql -u root -p{{ MARIADB_ROOT_PASSWORD }} -h {{ MARIADB_SVC_IP.stdout }} -e "DROP DATABASE IF EXISTS chub_tenant" --init-command="SET SESSION FOREIGN_KEY_CHECKS=0"
  tags:
    - check_maria
    - cleanup_db

- name: 5-3-4. Get SVC ip
  shell: /var/lib/rancher/rke2/bin/kubectl get svc mariadb -n db | awk '/mariadb/ {print $3}'
  register: MARIADB_SVC_IP
  tags:
    - check_maria
    - set_db

- name: 5-3-7. Add TMZ db
  shell: /var/lib/rancher/rke2/bin/kubectl exec -n db mariadb-primary-0 -- bash -c "mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p\{{ MARIADB_ROOT_PASSWORD }} mysql"
  tags:
    - check_maria
    - set_db

- name: 5-3-8. Create INIT schema
  shell: "mysql --init-command='SET SESSION FOREIGN_KEY_CHECKS=0;SET UNIQUE_CHECKS=0;SET GLOBAL KEY_BUFFER_SIZE=4024128128; SET BACKUP_RESTORE_CONCURRENCY=64;SET BACKUP_WRITE_COMPRESSION_LEVEL=1;' -u root -p{{ MARIADB_ROOT_PASSWORD }} -h {{ MARIADB_SVC_IP.stdout }} </root/manifest/sql/chub/init_mariadb.sql"
  ignore_errors: True
  tags:
    - check_maria
    - set_db

- name: 5-3-9. Setup Chub_CMS_SCHEME
  shell: "mysql --init-command='SET SESSION FOREIGN_KEY_CHECKS=0;SET UNIQUE_CHECKS=0;SET GLOBAL KEY_BUFFER_SIZE=4024128128; SET BACKUP_RESTORE_CONCURRENCY=64;SET BACKUP_WRITE_COMPRESSION_LEVEL=1;' -u root -p{{ MARIADB_ROOT_PASSWORD }} -h {{ MARIADB_SVC_IP.stdout }} chub_cms </root/manifest/sql/chub/chub_cms_scheme2.sql"
  tags:
    - check_maria
    - set_db

- name: 5-3-10. Setup Chub_CMS_DATA
  shell: "mysql --init-command='SET SESSION FOREIGN_KEY_CHECKS=0;SET UNIQUE_CHECKS=0;SET GLOBAL KEY_BUFFER_SIZE=4024128128; SET BACKUP_RESTORE_CONCURRENCY=64;SET BACKUP_WRITE_COMPRESSION_LEVEL=1;' -u root -p{{ MARIADB_ROOT_PASSWORD }} -h {{ MARIADB_SVC_IP.stdout }} chub_cms </root/manifest/sql/chub/chub_cms_data.sql"
  tags:
    - check_maria
    - set_db

- name: 5-3-11. Setup Chub_TENANT_SCHEME
  shell: "mysql --init-command='SET SESSION FOREIGN_KEY_CHECKS=0;SET UNIQUE_CHECKS=0;SET GLOBAL KEY_BUFFER_SIZE=4024128128; SET BACKUP_RESTORE_CONCURRENCY=64;SET BACKUP_WRITE_COMPRESSION_LEVEL=1;' -u root -p{{ MARIADB_ROOT_PASSWORD }} -h {{ MARIADB_SVC_IP.stdout }} chub_tenant </root/manifest/sql/chub/chub_tenant_scheme.sql"
  tags:
    - check_maria
    - set_db

- name: 5-3-12. Setup Chub_TENANT_DATA
  shell: "mysql --init-command='SET SESSION FOREIGN_KEY_CHECKS=0;SET UNIQUE_CHECKS=0;SET GLOBAL KEY_BUFFER_SIZE=4024128128; SET BACKUP_RESTORE_CONCURRENCY=64;SET BACKUP_WRITE_COMPRESSION_LEVEL=1;' -u root -p{{ MARIADB_ROOT_PASSWORD }} -h {{ MARIADB_SVC_IP.stdout }} chub_tenant </root/manifest/sql/chub/chub_tenant_data2.sql"
  tags:
    - check_maria
    - set_db

- name: 5-3-13. Setup master 
  shell: "mysql --init-command='SET SESSION FOREIGN_KEY_CHECKS=0;SET UNIQUE_CHECKS=0;SET GLOBAL KEY_BUFFER_SIZE=4024128128; SET BACKUP_RESTORE_CONCURRENCY=64;SET BACKUP_WRITE_COMPRESSION_LEVEL=1;' -u root -p{{ MARIADB_ROOT_PASSWORD }} -h {{ MARIADB_SVC_IP.stdout }} </root/manifest/sql/aibot/maria_db.sql"
  tags:
    - check_maria
    - set_db

- name: 5-3-14. Setup master_smp
  shell: "mysql --init-command='SET SESSION FOREIGN_KEY_CHECKS=0;SET UNIQUE_CHECKS=0;SET GLOBAL KEY_BUFFER_SIZE=4024128128; SET BACKUP_RESTORE_CONCURRENCY=64;SET BACKUP_WRITE_COMPRESSION_LEVEL=1;' -u root -p{{ MARIADB_ROOT_PASSWORD }} -h {{ MARIADB_SVC_IP.stdout }} </root/manifest/sql/amp/amp.sql"
  tags:
    - check_maria
    - set_db

- name: 5-3-14. Additional Authorization Setup
  shell: "mysql --init-command='SET SESSION FOREIGN_KEY_CHECKS=0;SET UNIQUE_CHECKS=0;SET GLOBAL KEY_BUFFER_SIZE=4024128128; SET BACKUP_RESTORE_CONCURRENCY=64;SET BACKUP_WRITE_COMPRESSION_LEVEL=1;' -u root -p{{ MARIADB_ROOT_PASSWORD }} -h {{ MARIADB_SVC_IP.stdout }} </root/manifest/sql/chub/end_mariadb.sql"
  tags:
    - check_maria
    - set_db
