# 노드들에 대해서 어플리케이션 배치에 필요한 Labels 및 의도되지 않은 배치가 진행되지 않도록 Taints를 진행합니다.
- name: 5-1-1. Set Labels
  shell: /var/lib/rancher/rke2/bin/kubectl label node {{ item.Nodes }} {{ item.Labels }}
  with_items:
    - { Nodes: "rke2-worker-node01", Labels: "application/instance-type=vas-stt" }
    - { Nodes: "rke2-worker-node02", Labels: "application/instance-type=vas-stt" }
    - { Nodes: "rke2-worker-node03", Labels: "application/instance-type=vas-tts" }
    - { Nodes: "rke2-worker-node04", Labels: "application/instance-type=vas-tts" }
    - { Nodes: "rke2-worker-node05", Labels: "solr=true" }
    - { Nodes: "rke2-worker-node06", Labels: "solr=true" }
    - { Nodes: "rke2-worker-node07", Labels: "solr=true" }
    - { Nodes: "rke2-worker-node05", Labels: "opensearch=true" }
    - { Nodes: "rke2-worker-node06", Labels: "opensearch=true" }
    - { Nodes: "rke2-worker-node07", Labels: "opensearch=true" }
    - { Nodes: "rke2-worker-node05", Labels: "redis=true" }
    - { Nodes: "rke2-worker-node06", Labels: "redis=true" }
    - { Nodes: "rke2-worker-node07", Labels: "redis=true" }
    - { Nodes: "rke2-db-node01", Labels: "db=true" }
  tags:
    - labels
    - application
    
- name: 5-1-2. Set Labels-role-worker
  shell: /var/lib/rancher/rke2/bin/kubectl label node {{ item }} node-role.kubernetes.io/worker=true
  with_items:
    - "rke2-worker-node01"
    - "rke2-worker-node02"
    - "rke2-worker-node03"
    - "rke2-worker-node04"
  tags:
    - labels
    - roles

- name: 5-1-3. Set taint
  shell: /var/lib/rancher/rke2/bin/kubectl taint node {{ item.Nodes }} {{ item.Taints }}
  with_items:
    - { Nodes: "rke2-db-node01", Taints: "db=true:NoSchedule" }
    - { Nodes: "rke2-worker-node05", Taints: "oss=true:NoSchedule" }
    - { Nodes: "rke2-worker-node06", Taints: "oss=true:NoSchedule" }
    - { Nodes: "rke2-worker-node07", Taints: "oss=true:NoSchedule" }
  tags:
    - labels
    - taints
