- name: 5-2-1. Directory setup
  file:
    path: "/root/helm_chart"
    state: directory
  tags:
    - oss_setup
    - set_resource_oss

- name: 5-2-2. git clone manifest repo
  shell: "git clone http://{{ ARGO_CONNECTED_SCM }} /root/manifest/"
  tags:
    - oss_setup
    - set_resource_oss

- name: 5-2-3. Copy yaml template"
  copy:
    src: "oss_yaml/{{ item.yaml }}"
    dest: "{{ item.dest }}"
  with_items:
    - { yaml: argocd-values.yaml, dest: /root/manifest/oss/argocd/argocd-values.yaml }
    - { yaml: mariadb-exporter.yaml, dest: /root/manifest/oss/mariadb-exporter/mariadb-exporter.yaml }
    - { yaml: mariadb-values.yaml, dest: /root/manifest/oss/mariadb/mariadb-values.yaml }
    - { yaml: opensearch-values.yaml, dest: /root/manifest/oss/opensearch/opensearch-values.yaml }
    - { yaml: redis-values.yaml, dest: /root/manifest/oss/redis/redis-values.yaml }
    - { yaml: zk-statefulset.yaml, dest: /root/manifest/oss/solr/zk-statefulset.yaml }
    - { yaml: solr-statefulset.yaml, dest: /root/manifest/oss/solr/solr-statefulset.yaml }
    - { yaml: solr-ingress.yaml, dest: /root/manifest/oss/solr/solr-ingress.yaml }
    - { yaml: dashboard-ingress.yaml, dest: /root/manifest/oss/opensearch/dashboard-ingress.yaml }
    - { yaml: grafana-ingress.yaml, dest: /root/manifest/oss/rancher-monitoring/grafana-ingress.yaml }
    - { yaml: custom-values.yaml, dest: /root/manifest/oss/fluent-bit/daemonset/custom-values.yaml }
    - { yaml: opensearch_IMS.sh, dest: /tmp/opensearch_IMS.sh }
  tags:
    - oss_setup
    - set_resource_oss

- name: 5-2-4. Change yaml template"
  shell: |
    sed -i 's,REGISTRYIP,{{ REGISTRY_URL }}:{{ REGISTRY_PORT }},g' {{ item.dest }}
    sed -i 's,HOSTIP,{{ DOMAIN_NAME }},g' {{ item.dest }}
  with_items:
    - { yaml: mariadb-exporter.yaml, dest: /root/manifest/oss/mariadb-exporter/mariadb-exporter.yaml }
    - { yaml: mariadb-values.yaml, dest: /root/manifest/oss/mariadb/mariadb-values.yaml }
    - { yaml: opensearch-values.yaml, dest: /root/manifest/oss/opensearch/opensearch-values.yaml }
    - { yaml: redis-values.yaml, dest: /root/manifest/oss/redis/redis-values.yaml }
    - { yaml: zk-statefulset.yaml, dest: /root/manifest/oss/solr/zk-statefulset.yaml }
    - { yaml: solr-statefulset.yaml, dest: /root/manifest/oss/solr/solr-statefulset.yaml }
    - { yaml: solr-ingress.yaml, dest: /root/manifest/oss/solr/solr-ingress.yaml }
    - { yaml: dashboard-ingress.yaml, dest: /root/manifest/oss/opensearch/dashboard-ingress.yaml }
    - { yaml: grafana-ingress.yaml, dest: /root/manifest/oss/rancher-monitoring/grafana-ingress.yaml }
    - { yaml: custom-values.yaml, dest: /root/manifest/oss/fluent-bit/daemonset/custom-values.yaml }
  tags:
    - oss_setup
    - set_resource_oss
    # - { yaml: argocd-values.yaml, dest: /root/manifest/oss/argocd/argocd-values.yaml }
# Helm에 Nexus에 게시된 Private Helm 저장소를 추가합니다.
- name: 5-2-5. Set helm repo
  shell: |
    /usr/local/bin/helm repo add aicc http://{{ REGISTRY_URL }}:{{ HELM_PORT }}/repository/helm-hosted
    sed -i 's/HOSTIP/{{ ansible_facts.default_ipv4.address }}/g' /root/manifest/oss/argocd/argocd-values.yaml
    sed -i 's/REGISTRYIP/{{ REGISTRY_URL }}:{{ REGISTRY_PORT }}/g' /root/manifest/oss/argocd/argocd-values.yaml
  tags:
    - oss_setup
    - set_helm

# 오픈소스 앱들 중 DB 역할을 하는 어플리케이션들을 배포합니다.
- name: 5-2-6. OpenSource Deploy
  shell: /usr/local/bin/helm install {{ item.name }} aicc/{{ item.repo_name }} -n {{ item.ns }} --create-namespace -f {{ item.values_file }} --timeout=10m0s
  with_items:
    - { ns: argocd, name: argocd, repo_name: argo-cd, values_file: /root/manifest/oss/argocd/argocd-values.yaml }
    - { ns: db, name: mariadb, repo_name: mariadb, values_file: /root/manifest/oss/mariadb/mariadb-values.yaml }
    - { ns: opensearch, name: opensearch, repo_name: opensearch, values_file: /root/manifest/oss/opensearch/opensearch-values.yaml }
    - { ns: redis, name: redis, repo_name: redis-cluster, values_file: /root/manifest/oss/redis/redis-values.yaml }
  tags:
    - oss_setup
    - deploy_db

# 외부 서비스에 대한 모니터링을 돕는 하는 BlackBox exporter를 배포합니다.
- name: 5-2-7. blackbox exporter
  shell: /usr/local/bin/helm install blackbox-exporter aicc/prometheus-blackbox-exporter -n cattle-monitoring-system --create-namespace --set image.registry="{{ REGISTRY_URL }}:5000" --set image.repository="third-party/prom/blackbox-exporter" --set image.tags="v0.24.0"
  tags:
    - oss_setup
    - monitoring

# K8S Management 도구인 랜처와 텍스트 데이터 수집 역할을 하는 Solr를 배포합니다.
- name: 5-2-8. Rancher & Monitoring & Solr Deploy
  shell: "{{ item }}"
  with_items:
    - "/usr/local/bin/helm install rancher aicc/rancher -n cattle-system --set hostname={{ ansible_facts.default_ipv4.address }}.nip.io --set replicas=1 --set bootstrapPassword={{ RANCHER_ADMIN_PASSWORD }}"
    - /var/lib/rancher/rke2/bin/kubectl create namespace solr
    - /var/lib/rancher/rke2/bin/kubectl apply -k /root/manifest/oss/solr/ -n solr
    - /var/lib/rancher/rke2/bin/kubectl apply -f /root/manifest/oss/mariadb-exporter/mariadb-exporter.yaml -n db
    - /var/lib/rancher/rke2/bin/kubectl cp /tmp/opensearch_IMS.sh -n opensearch opensearch-master-0:/tmp
    - /var/lib/rancher/rke2/bin/kubectl -n opensearch  exec -it opensearch-master-0 -- /bin/sh -c 'sh /tmp/opensearch_IMS.sh'
  tags:
    - oss_setup
    - monitoring

# mariadb 서비스와 Grafana Dashboard를 배포합니다.
- name: 5-2-9. Dashboards Deploy
  shell: /var/lib/rancher/rke2/bin/kubectl apply -f {{ item.values_file }} -n {{ item.ns }}
  with_items:
    - { values_file: /root/manifest/oss/opensearch/dashboard-ingress.yaml, ns: opensearch }
    - { values_file: /root/manifest/oss/mariadb/mariadb-svc.yaml, ns: db }
  tags:
    - oss_setup
    - deploy_dashboard
