apiVersion: apps/v1
kind: Deployment
metadata:
  name: aibot-scheduler-deployment
  namespace: vas-aibot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aibot-scheduler-app
  template:
    metadata:
      labels:
        app: aibot-scheduler-app
    spec:
      restartPolicy: Always
      nodeSelector:
        node-role.kubernetes.io/worker: "true"

      containers:
      - name: aibot-scheduler-app
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        image: "{{ REGISTRY_URL }}:{{ REGISTRY_PORT }}/vas/aibot/scheduler:{{ AIBOT_VER }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: server-aibot-scheduler-log-volume
          mountPath: /jb_log
      - name: aibot-scheduler-fluent-bit
        image: "{{ REGISTRY_URL }}:{{ REGISTRY_PORT }}/bitnami/fluent-bit:2.2.0"
        volumeMounts:
        - name: server-aibot-scheduler-log-volume
          mountPath: /jb_log
        - name: aibot-scheduler-fluentbit-config
          mountPath: /opt/bitnami/fluent-bit/conf/fluent-bit.conf
          subPath: fluent-bit.conf
        - name: aibot-scheduler-fluentbit-parser
          mountPath: /opt/bitnami/fluent-bit/conf/aibot-parsers.conf
          subPath: aibot-parsers.conf

      volumes:
      - name: server-aibot-scheduler-log-volume
        emptyDir: {}
      - name: aibot-scheduler-fluentbit-config
        configMap:
          name: aibot-scheduler-fluentbit-configmap
          items:
          - key: fluent-bit.conf
            path: fluent-bit.conf
      - name: aibot-scheduler-fluentbit-parser
        configMap:
          name: aibot-scheduler-fluentbit-configmap
          items:
          - key: aibot-parsers.conf
            path: aibot-parsers.conf
