disabled_plugins = []
[plugins."io.containerd.grpc.v1.cri".registry]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
      endpoint = ["http://{{ REGISTRY_URL }}:{{ REGISTRY_PORT }}"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."quay.io"]
      endpoint = ["http://{{ REGISTRY_URL }}:{{ REGISTRY_PORT }}"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."{{ REGISTRY_URL }}:{{ REGISTRY_PORT }}"]
      endpoint = ["http://{{ REGISTRY_URL }}:{{ REGISTRY_PORT }}"]
  [plugins."io.containerd.grpc.v1.cri".registry.configs]
    [plugins."io.containerd.grpc.v1.cri".registry.configs."{{ REGISTRY_URL }}:{{ REGISTRY_PORT }}".auth]
      username = "{{ REGISTRY_ID }}"
      password = "{{ REGISTRY_PASSWD }}"
    [plugins."io.containerd.grpc.v1.cri".registry.configs."{{ REGISTRY_URL }}:{{ REGISTRY_PORT }}".tls]
      insecure_skip_verify = true