architecture: standalone

image:
  registry: "{{ REGISTRY_URL }}:{{ REGISTRY_PORT }}"
  repository: third-party/mariadb
  tag: 10.6.10-debian-11-r16

auth:
  rootPassword: "admin12341234"

primary:
  configuration: |-
    [mysqld]
    lower_case_table_names=1
    default-time-zone = '+9:00'
    character-set-server=UTF8
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mariadb
    plugin_dir=/opt/bitnami/mariadb/plugin
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    tmpdir=/opt/bitnami/mariadb/tmp
    max_allowed_packet=16M
    bind-address=*
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    log-error=/opt/bitnami/mariadb/logs/mysqld.log
    collation-server=utf8_general_ci
    slow_query_log=0
    slow_query_log_file=/opt/bitnami/mariadb/logs/mysqld.log
    long_query_time=10.0

    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mariadb/plugin

    [manager]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
  nodeSelector: "db: 'true'"
  resources:
    requests:
      cpu: "4"
      memory: "16Gi"
    limits:
      cpu: "4"
      memory: "16Gi"
  persistence:
    storageClass: "longhorn"
    size: "10Gi"
    accessModes:
    - "ReadWriteMany"
  tolerations:
  - key: "db"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  readinessProbe:
    exec:
      command:
      - /bin/bash
      - -ec
      - |
        password_aux="${MARIADB_ROOT_PASSWORD:-}"
        if [[ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]]; then
            password_aux=$(cat "$MARIADB_ROOT_PASSWORD_FILE")
        fi
        mysqladmin status -uroot -p"${password_aux}"
    failureThreshold: 3
    initialDelaySeconds: 40
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
# metrics:
#   enabled: "true"
#   image:
#     registry: {{ REGISTRY_URL }}:{{ REGISTRY_PORT }}
#     repository: third-party/prom/mysqld-exporter
#     tag: v0.15.0
#   annotations:
#     prometheus.io/scrape: "true"
#     prometheus.io/port: "9104"
#   labels:
#     app: "mysqld-exporter"
#   extraArgs:
#     primary: []
#   extraVolumeMounts:
#     primary: []
      # - --config.my-cnf=/etc/.mysqld_exporter.cnf
      # - --mysqld.address=mariadb.db.svc.cluster.local:3306
      # - --collect.info_schema.tables
      # - --collect.info_schema.innodb_metrics
      # - --collect.global_status
      # - --collect.global_variables
      # - --collect.slave_status
      # - --collect.info_schema.processlist
      # - --collect.perf_schema.tablelocks
      # - --collect.perf_schema.eventsstatements
      # - --collect.perf_schema.eventswaits
      # - --collect.auto_increment.columns
      # - --collect.binlog_size
      # - --collect.perf_schema.tableiowaits
      # - --collect.perf_schema.indexiowaits
      # - --collect.info_schema.userstats
      # - --collect.info_schema.clientstats
      # - --collect.info_schema.tablestats
      # - --collect.info_schema.schemastats
      # - --collect.perf_schema.file_events
      # - --collect.perf_schema.file_instances
      # - --collect.info_schema.innodb_cmp
      # - --collect.info_schema.innodb_cmpmem
      # - --collect.info_schema.query_response_time
      # - --collect.engine_innodb_status
