- name: 4-4-1. Copy argocd binary
  copy: 
    src: "{{ LOCAL_PATH.PACKAGES }}/argocd"
    dest: /usr/local/bin/argocd
  tags:
    - deploy_argocd
    - get_resource

- name: 4-4-1-1. Copy yaml
  template:
    src:  "argocd_yaml/{{ item.yaml }}"
    dest: "{{ item.dest }}"
  with_items:
    - { yaml: chub/agw/chub-agw-config-deploy.yaml , dest: /root/manifest/chub/agw/chub-agw-config-deploy.yaml }
    - { yaml: chub/agw/chub-agw-discovery-deploy.yaml , dest: /root/manifest/chub/agw/chub-agw-discovery-deploy.yaml }
    - { yaml: chub/agw/chub-agw-scg-deploy.yaml , dest: /root/manifest/chub/agw/chub-agw-scg-deploy.yaml }
    - { yaml: chub/cms/chub-cms-api-deploy.yaml , dest: /root/manifest/chub/cms/chub-cms-api-deploy.yaml }
    - { yaml: chub/cms/chub-cms-ui-deploy.yaml , dest: /root/manifest/chub/cms/chub-cms-ui-deploy.yaml }
    - { yaml: chub/cms/chub-cms-ui-ingress.yaml , dest: /root/manifest/chub/cms/chub-cms-ui-ingress.yaml }
    - { yaml: chub/consumer/chub-consumer-deploy.yaml , dest: /root/manifest/chub/consumer/chub-consumer-deploy.yaml }
    - { yaml: chub/sgw/chub-sgw-deploy.yaml , dest: /root/manifest/chub/sgw/chub-sgw-deploy.yaml }
    - { yaml: chub/tsm/chub-tsm-restapi-deploy.yaml , dest: /root/manifest/chub/tsm/chub-tsm-restapi-deploy.yaml }
    - { yaml: chub/vgw/vgw-deployment.yaml , dest: /root/manifest/chub/vgw/vgw-deployment.yaml }
    - { yaml: tts/tts-cck-deploy.yaml , dest: /root/manifest/tts/tts-cck-deploy.yaml }
    - { yaml: stt/cpod/stt-cpod-deploy.yaml , dest: /root/manifest/stt/cpod/stt-cpod-deploy.yaml }
    - { yaml: stt/epod/stt-epod-deploy.yaml , dest: /root/manifest/stt/epod/stt-epod-deploy.yaml }
    - { yaml: stt/mpod/stt-mpod-deploy.yaml , dest: /root/manifest/stt/mpod/stt-mpod-deploy.yaml }
    - { yaml: aibot/scheduler/aibot-scheduler-deploy.yaml , dest: /root/manifest/aibot/scheduler/aibot-scheduler-deploy.yaml }
    - { yaml: aibot/master/aibot-master-deploy.yaml , dest: /root/manifest/aibot/master/aibot-master-deploy.yaml }
    - { yaml: aibot/master/aibot-master-configmap.yaml , dest: /root/manifest/aibot/master/aibot-master-configmap.yaml }
    - { yaml: aibot/gateway/aibot-gateway-deploy.yaml , dest: /root/manifest/aibot/gateway/aibot-gateway-deploy.yaml }
    - { yaml: aibot/engine/aibot-engine-deploy.yaml , dest: /root/manifest/aibot/engine/aibot-engine-deploy.yaml }
    - { yaml: aibot/cms/aibot-cms-configmap.yaml , dest: /root/manifest/aibot/cms/aibot-cms-configmap.yaml }
    - { yaml: aibot/cms/aibot-cms-deploy.yaml , dest: /root/manifest/aibot/cms/aibot-cms-deploy.yaml }
    - { yaml: aibot/cms/aibot-cms-ingress.yaml , dest: /root/manifest/aibot/cms/aibot-cms-ingress.yaml }
    - { yaml: aibot/chat-ui/aibot-chat-ui-deploy.yaml , dest: /root/manifest/aibot/chat-ui/aibot-chat-ui-deploy.yaml }
    - { yaml: aibot/chat-ui/aibot-chat-ui-ingress.yaml , dest: /root/manifest/aibot/chat-ui/aibot-chat-ui-ingress.yaml }
    - { yaml: aibot/chat-ui/aibot-chat-ui-ingress.yaml , dest: /root/manifest/aibot/chat-ui/aibot-chat-ui-ingress.yaml }
    - { yaml: kube-state-metric/kube-state-deployment.yaml , dest: /root/manifest/oss/monitoring/kube-state-metric/kube-state-deployment.yaml }
    - { yaml: metrics-agent/metrics-agent-deploy.yaml , dest: /root/manifest/oss/monitoring/metrics-agent/metrics-agent-deploy.yaml }
    - { yaml: metrics-agent/metrics-agent-ingress.yaml , dest: /root/manifest/oss/monitoring/metrics-agent/metrics-agent-ingress.yaml }
    - { yaml: metrics-agent/metrics-agent-configmap.yaml , dest: /root/manifest/oss/monitoring/metrics-agent/metrics-agent-configmap.yaml }
    - { yaml: prometheus/prometheus-deployment.yaml , dest: /root/manifest/oss/monitoring/prometheus/prometheus-deployment.yaml }
    - { yaml: prometheus/prometheus-grafana.yaml , dest: /root/manifest/oss/monitoring/prometheus/prometheus-grafana.yaml }
    - { yaml: prometheus/prometheus-ingress.yaml , dest: /root/manifest/oss/monitoring/prometheus/prometheus-ingress.yaml }
    - { yaml: prometheus/prometheus-node-exporter.yaml , dest: /root/manifest/oss/monitoring/prometheus/prometheus-node-exporter.yaml }
  tags:
    - deploy_argocd
    - git_resource

- name: 4-4-1-1. Change yaml
  shell: |
    sed -i 's,REGISTRYIP,{{ REGISTRY_URL }}:{{ REGISTRY_PORT }},g' {{ item.dest }}
    sed -i 's,HOSTIP,{{ DOMAIN_NAME }},g' {{ item.dest }}
    sed -i 's,AIBOT_VER,{{ AIBOT_VER }},g' {{ item.dest }}
  with_items:
    - { yaml: chub/agw/chub-agw-config-deploy.yaml , dest: /root/manifest/chub/agw/chub-agw-config-deploy.yaml }
    - { yaml: chub/agw/chub-agw-discovery-deploy.yaml , dest: /root/manifest/chub/agw/chub-agw-discovery-deploy.yaml }
    - { yaml: chub/agw/chub-agw-scg-deploy.yaml , dest: /root/manifest/chub/agw/chub-agw-scg-deploy.yaml }
    - { yaml: chub/cms/chub-cms-api-deploy.yaml , dest: /root/manifest/chub/cms/chub-cms-api-deploy.yaml }
    - { yaml: chub/cms/chub-cms-ui-deploy.yaml , dest: /root/manifest/chub/cms/chub-cms-ui-deploy.yaml }
    - { yaml: chub/cms/chub-cms-ui-ingress.yaml , dest: /root/manifest/chub/cms/chub-cms-ui-ingress.yaml }
    - { yaml: chub/consumer/chub-consumer-deploy.yaml , dest: /root/manifest/chub/consumer/chub-consumer-deploy.yaml }
    - { yaml: chub/sgw/chub-sgw-deploy.yaml , dest: /root/manifest/chub/sgw/chub-sgw-deploy.yaml }
    - { yaml: chub/tsm/chub-tsm-restapi-deploy.yaml , dest: /root/manifest/chub/tsm/chub-tsm-restapi-deploy.yaml }
    - { yaml: chub/vgw/vgw-deployment.yaml , dest: /root/manifest/chub/vgw/vgw-deployment.yaml }
    - { yaml: tts/tts-cck-deploy.yaml , dest: /root/manifest/tts/tts-cck-deploy.yaml }
    - { yaml: stt/cpod/stt-cpod-deploy.yaml , dest: /root/manifest/stt/cpod/stt-cpod-deploy.yaml }
    - { yaml: stt/epod/stt-epod-deploy.yaml , dest: /root/manifest/stt/epod/stt-epod-deploy.yaml }
    - { yaml: stt/mpod/stt-mpod-deploy.yaml , dest: /root/manifest/stt/mpod/stt-mpod-deploy.yaml }
    - { yaml: aibot/scheduler/aibot-scheduler-deploy.yaml , dest: /root/manifest/aibot/scheduler/aibot-scheduler-deploy.yaml }
    - { yaml: aibot/master/aibot-master-deploy.yaml , dest: /root/manifest/aibot/master/aibot-master-deploy.yaml }
    - { yaml: aibot/master/aibot-master-configmap.yaml , dest: /root/manifest/aibot/master/aibot-master-configmap.yaml }
    - { yaml: aibot/gateway/aibot-gateway-deploy.yaml , dest: /root/manifest/aibot/gateway/aibot-gateway-deploy.yaml }
    - { yaml: aibot/engine/aibot-engine-deploy.yaml , dest: /root/manifest/aibot/engine/aibot-engine-deploy.yaml }
    - { yaml: aibot/cms/aibot-cms-configmap.yaml , dest: /root/manifest/aibot/cms/aibot-cms-configmap.yaml }
    - { yaml: aibot/cms/aibot-cms-deploy.yaml , dest: /root/manifest/aibot/cms/aibot-cms-deploy.yaml }
    - { yaml: aibot/cms/aibot-cms-ingress.yaml , dest: /root/manifest/aibot/cms/aibot-cms-ingress.yaml }
    - { yaml: aibot/chat-ui/aibot-chat-ui-deploy.yaml , dest: /root/manifest/aibot/chat-ui/aibot-chat-ui-deploy.yaml }
    - { yaml: aibot/chat-ui/aibot-chat-ui-ingress.yaml , dest: /root/manifest/aibot/chat-ui/aibot-chat-ui-ingress.yaml }
    - { yaml: aibot/chat-ui/aibot-chat-ui-ingress.yaml , dest: /root/manifest/aibot/chat-ui/aibot-chat-ui-ingress.yaml }
    - { yaml: kube-state-metric/kube-state-deployment.yaml , dest: /root/manifest/oss/monitoring/kube-state-metric/kube-state-deployment.yaml }
    - { yaml: metrics-agent/metrics-agent-deploy.yaml , dest: /root/manifest/oss/monitoring/metrics-agent/metrics-agent-deploy.yaml }
    - { yaml: metrics-agent/metrics-agent-ingress.yaml , dest: /root/manifest/oss/monitoring/metrics-agent/metrics-agent-ingress.yaml }
    - { yaml: metrics-agent/metrics-agent-configmap.yaml , dest: /root/manifest/oss/monitoring/metrics-agent/metrics-agent-configmap.yaml }
    - { yaml: prometheus/prometheus-deployment.yaml , dest: /root/manifest/oss/monitoring/prometheus/prometheus-deployment.yaml }
    - { yaml: prometheus/prometheus-grafana.yaml , dest: /root/manifest/oss/monitoring/prometheus/prometheus-grafana.yaml }
    - { yaml: prometheus/prometheus-ingress.yaml , dest: /root/manifest/oss/monitoring/prometheus/prometheus-ingress.yaml }
    - { yaml: prometheus/prometheus-node-exporter.yaml , dest: /root/manifest/oss/monitoring/prometheus/prometheus-node-exporter.yaml }
  tags:
    - deploy_argocd
    - git_resource
    
- name: 4-4-1-2. git commit
  shell: git commit -am "update env on yamls"
  tags:
    - deploy_argocd
    - git_resource

- name: 4-4-1-3. git push
  shell: |
    git push http://{{ GITEA_USER }}:{{ GITEA_PASSWD }}@{{ GITEA_URL }}/gitea/manifest.git
  tags:
    - deploy_argocd
    - git_resource
# ArgoCD CLI Change Permissions
- name: 4-4-2. Change file permissions
  file:
    path: /usr/local/bin/argocd
    mode: '0755'
  tags:
    - deploy_argocd
    - set_argocd

# TODO: username, password 설정
- name: 4-4-3. ArgoCD
  shell: |
    argocd login argocd.{{ ansible_facts.default_ipv4.address }}.nip.io --username {{ ARGO_USER }} --password {{ ARGO_PASSWORD }} --insecure
  tags:
    - deploy_argocd
    - set_argocd

- name: 4-4-4. Git Connection
  shell: |
    argocd repo add http://{{ ARGO_CONNECTED_SCM }}
  tags:
    - deploy_argocd
    - set_argocd

## C-Hub
- name: 4-4-5. Deploy C-Hub
  shell: |
    argocd app create {{ item.app }} \
    --repo http://{{ ARGO_CONNECTED_SCM }} \
    --path {{ item.path }} \
    --dest-server {{ CLUSTER_IP }} \
    --dest-namespace {{ item.ns }} \
    --sync-policy automated \
    --sync-option CreateNamespace=true \
    --auto-prune
  with_items:
    - { app: 'vas-chub-agw', path: 'chub/agw', ns: 'vas-chub' }
    - { app: 'vas-chub-cms', path: 'chub/cms', ns: 'vas-chub' }
    - { app: 'vas-chub-consumer', path: 'chub/consumer', ns: 'vas-chub' }
    - { app: 'vas-chub-sgw', path: 'chub/sgw', ns: 'vas-chub' }
    - { app: 'vas-chub-tsm', path: 'chub/tsm', ns: 'vas-chub' }
  tags:
    - deploy_argocd
    - deploy_chub

  ## TTS
- name: 4-4-6. Deploy TTS
  shell: |
    argocd app create {{ item.app }} \
    --repo http://{{ ARGO_CONNECTED_SCM }} \
    --path {{ item.path }} \
    --dest-server {{ CLUSTER_IP }} \
    --dest-namespace {{ item.ns }} \
    --sync-policy automated \
    --sync-option CreateNamespace=true \
    --auto-prune
  with_items:
    - { app: 'vas-tts', path: 'tts', ns: 'vas-tts' }
  tags:
    - deploy_argocd
    - deploy_tts

  ## STT
- name: 4-4-7. Deploy STT
  shell: |
    argocd app create {{ item.app }} \
    --repo http://{{ ARGO_CONNECTED_SCM }} \
    --path {{ item.path }} \
    --dest-server {{ CLUSTER_IP }} \
    --dest-namespace {{ item.ns }} \
    --sync-policy automated \
    --sync-option CreateNamespace=true \
    --auto-prune
  with_items:
    - { app: 'vas-stt', path: 'stt', ns: 'vas-stt' }
  tags:
    - deploy_argocd
    - deploy_stt

  ## Ai Bot
- name: 4-4-8. Deploy AI Bot
  shell: |
    argocd app create {{ item.app }} \
    --repo http://{{ ARGO_CONNECTED_SCM }} \
    --path {{ item.path }} \
    --dest-server {{ CLUSTER_IP }} \
    --dest-namespace {{ item.ns }} \
    --sync-policy automated \
    --sync-option CreateNamespace=true \
    --auto-prune      
  with_items:
    - { app: 'vas-aibot-chat-ui', path: 'aibot/chat-ui', ns: 'vas-aibot' }
    - { app: 'vas-aibot-cms', path: 'aibot/cms', ns: 'vas-aibot' }
    - { app: 'vas-aibot-engine', path: 'aibot/engine', ns: 'vas-aibot' }
    - { app: 'vas-aibot-gateway', path: 'aibot/gateway', ns: 'vas-aibot' }
    - { app: 'vas-aibot-master', path: 'aibot/master', ns: 'vas-aibot' }
    - { app: 'vas-aibot-scheduler', path: 'aibot/scheduler', ns: 'vas-aibot' }
  tags:
    - deploy_argocd
    - deploy_aibot

- name: 4-4-9. Deploy AMP
  shell: |
    argocd app create {{ item.app }} \
    --repo http://{{ ARGO_CONNECTED_SCM }} \
    --path {{ item.path }} \
    --dest-server {{ CLUSTER_IP }} \
    --dest-namespace {{ item.ns }} \
    --sync-policy automated \
    --sync-option CreateNamespace=true \
    --auto-prune      
  with_items:
    - { app: 'vas-amp-amp', path: 'amp/amp', ns: 'vas-amp' }
    - { app: 'vas-amp-stt', path: 'amp/smp/stt', ns: 'vas-stt' }
    - { app: 'vas-amp-tts', path: 'amp/smp/tts', ns: 'vas-tts' }
  tags:
    - deploy_argocd
    - deploy_amp