apiVersion: apps/v1
kind: Deployment
metadata:
  name: aibot-gateway-deployment
  namespace: vas-aibot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aibot-gateway-app
  template:
    metadata:
      labels:
        app: aibot-gateway-app
    spec:
      restartPolicy: Always
      nodeSelector:
        node-role.kubernetes.io/worker: "true"

      containers:
      - name: aibot-gateway-app
        image: "{{ REGISTRY_URL }}:5000/vas/aibot/gateway:{{ AIBOT_VER }}"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "4"
            memory: "8Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: app-aibot-gateway-log-volume
          mountPath: /data/logs
        - name: server-aibot-gateway-log-volume
          mountPath: /jb_log
      - name: aibot-gateway-fluent-bit
        image: "{{ REGISTRY_URL }}:5000/bitnami/fluent-bit:2.2.0"
        volumeMounts:
        - name: app-aibot-gateway-log-volume
          mountPath: /data/logs
        - name: server-aibot-gateway-log-volume
          mountPath: /jb_log
        - name: aibot-gateway-fluentbit-config
          mountPath: /opt/bitnami/fluent-bit/conf/fluent-bit.conf
          subPath: fluent-bit.conf
        - name: aibot-gateway-fluentbit-parser
          mountPath: /opt/bitnami/fluent-bit/conf/aibot-parsers.conf
          subPath: aibot-parsers.conf
        - name: aibot-gateway-fluentbit-script
          mountPath: /opt/bitnami/fluent-bit/conf/script.lua
          subPath: script.lua

      volumes:
      - name: app-aibot-gateway-log-volume
        emptyDir: {}
      - name: server-aibot-gateway-log-volume
        emptyDir: {}
      - name: aibot-gateway-fluentbit-config
        configMap:
          name: aibot-gateway-fluentbit-configmap
          items:
          - key: fluent-bit.conf
            path: fluent-bit.conf
      - name: aibot-gateway-fluentbit-parser
        configMap:
          name: aibot-gateway-fluentbit-configmap
          items:
          - key: aibot-parsers.conf
            path: aibot-parsers.conf
      - name: aibot-gateway-fluentbit-script
        configMap:
          name: aibot-gateway-fluentbit-configmap
          items:
          - key: script.lua
            path: script.lua
