## 02_download_resources
- name: 2-0-1. Copy Kernel Params
  file:
    src: sysctl.conf
    dest: /etc/sysctl.conf
  tags:
    - masters-init
    - system-params

- name: 2-0-2. apply Kernel Params
  shell: |
    sysctl -p /etc/sysctl.conf
  tags:
    - masters-init
    - system-params
    
## 07_install_configure_rke2
- name: 1-4-1. Uninstall RKE2
  shell: rke2-uninstall.sh
  tags:
    - masters_init
    - rke2-init

- name: 1-4-2. Install and set RKE2
  shell: INSTALL_RKE2_TYPE=server INSTALL_RKE2_ARTIFACT_PATH=/root/rke2-artifacts INSTALL_RKE2_SYSTEM_DEFAULT_REGISTRY="{{ REGISTRY_URL }}{{ ':' }}5000" sh /root/rke2-artifacts/install.sh
  tags:
    - masters_init
    - rke2-init

## 08_configure_registry
- name: 1-4-3. Create directories(Docker, RKE2, containerd)
  file:
    path: "{{ item.DIR }}"
    state: directory
  with_items: "{{ REGISTRY_CONFIG }}"
  tags:
    - masters_init
    - rke2-init

- name: 1-4-4. Set private repo for (Docker, RKE2, containerd)
  copy:
    dest: "{{ item.DIR }}/{{ item.FILE }}"
    content: "{{ item.CONTENT }}"
  with_items: "{{ REGISTRY_CONFIG }}"
  tags:
    - masters_init
    - rke2-init

## 09_configure_server
- name: 1-4-5. Make necessary directories
  file:
    path: /etc/rancher/rke2
    state: directory
  tags:
    - masters_init
    - rke2-init

- name: 1-4-6. Add the content to the file
  copy:
    dest: /etc/rancher/rke2/config.yaml
    content: |
      node-name: {{ inventory_hostname }}
  tags:
    - masters_init
    - rke2-init

- name: 1-4-7. Enable and start the rke2-server service
  systemd_service:
    name: rke2-server
    state: started
    enabled: true
  register: "check_rke2server_state"
  tags:
    - masters_init
    - rke2-init

- name: 1-4-8. Print rke2-server service status
  debug:
    msg: "{{ check_rke2server_state }}"
  tags:
    - masters_init
    - rke2-init

## 10_configure_kube_tools
- name: 1-5-1. Make log directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /var/log/vas
    - /root/.kube
  tags:
    - masters_init
    - config-kubeconfig

- name: 1-5-2. Set Up Kubeconfig
  copy:
    src: /etc/rancher/rke2/rke2.yaml
    dest: /root/.kube/config
    mode: 0600
    remote_src: yes
  tags:
    - masters_init
    - config-kubeconfig

- name: 1-6-1. Display the cluster token from the file and emphasize it
  shell: cat /var/lib/rancher/rke2/server/node-token
  register: node_token
  tags:
    - masters_init
    - prepare-connect

- name: 1-6-2. Print node token
  debug:
    msg: "Cluster token{{ ':' }} {{ node_token.stdout }}"
  tags:
    - masters_init
    - prepare-connect

- name: 1-6-3. Copy node token from the master to the controller
  fetch:
    src: "/var/lib/rancher/rke2/server/token"
    dest: "{{ LOCAL_PATH.BASE }}/node-token/token"
    flat: yes
  tags:
    - masters_init
    - prepare-connect

## 11_install_configure tools
- name: 1-7-1. Copy configuration tool files
  copy:
    src: "{{ item.SRC }}"
    dest: "/usr/local/bin/{{ item.DEST }}"
    mode: +x
    remote_src: yes
  with_items: "{{ CONFIG_TOOL_FILES_M }}"
  tags:
    - masters_init
    - config-kubetools
  
- name: 1-7-4. Enable iscsid
  systemd_service:
    name: iscsid
    state: started
    enabled: true
  tags:
    - masters_init
    - config-kubetools
  
- name: 1-7-5. configuration environment
  lineinfile:
    path: /root/.bashrc
    line: "{{ item }}"
  with_items:
    - "export PATH=$PATH:/var/lib/rancher/rke2/bin:/usr/local/bin"
    - "export CRI_CONFIG_FILE=/var/lib/rancher/rke2/agent/etc/crictl.yaml"
    - "alias k=kubectl"
  tags:
    - masters_init
    - config-kubetools
  
- name: 1-7-6. Source bashrc
  shell: source /root/.bashrc
  tags:
    - masters_init
    - config-kubetools
  
- name: 1-7-7. Install cert manager
  shell: "/var/lib/rancher/rke2/bin/kubectl apply -f {{ LOCAL_PATH.BASE }}/yaml/cert-manager.yaml"
  tags:
    - masters_init
    - config-kubetools
  
- name: 1-7-8. Pause for 1 minute to run cert-manager
  pause:
    minutes: 1
    prompt: "Please wait 1 min for run cert-manager service"
  tags:
    - masters_init
    - config-kubetools
  
- name: 1-7-9. Install rancher
  shell: /var/lib/rancher/rke2/bin/kubectl apply -f {{ LOCAL_PATH.BASE }}/yaml/cattle-system-ns.yaml
  tags:
    - masters_init
    - config-kubetools
  
- name: 1-7-10. Install longhorn
  shell: "/var/lib/rancher/rke2/bin/kubectl apply -f {{ LOCAL_PATH.BASE }}/yaml/longhorn.yaml"
  tags:
    - masters_init
    - config-kubetools
- name: 1-7-11. set hostname
  hostname: 
    name: "{{ inventory_hostname }}"
  tags:
    - masters_init
    - config-kubetools