- name: get command
  copy: 
    src: '/tmp/JOIN_COMMAND_M'
    dest: '/tmp/JOIN_COMMAND_M'
  tags:
    - k8s_connect

- name: get kube-cert
  shell: "kubeadm init phase certs all --apiserver-advertise-address={{ BASTION_NODE_IP }}"

- name: kubeadm connect
  shell: '. /tmp/JOIN_COMMAND_M' 
  register: INIT_COMMAND
  tags:
    - k8s_connect

- name: create directory
  file:
    path: '/root/.kube/'
    state: directory  
  tags:
    - k8s_connect

- name: kubeadm init - debug
  debug:
    msg: "{{ INIT_COMMAND }}"
  tags:
    - k8s_connect

- name: copy resource
  copy:
    src: "k8s_yaml"
    dest: "/root/"
  tags:
    - k8s_connect

- name: extract tools
  unarchive:
    src: 'k8s_yaml/helm-v3.13.3-linux-amd64.tar.gz'
    dest: '/root/k8s_yaml/'
  tags:
    - k8s_connect

- name: mv helm
  copy: 
    src: '/root/k8s_yaml/linux-amd64/helm'
    dest: '/usr/local/bin/helm'
    remote_src: yes
  tags:
    - k8s_connect

- name: set Kubeconfig
  blockinfile:
    path: '/etc/bash.bashrc'
  #    path: '/root/.bashrc'
    block: |
      export KUBECONFIG=/etc/kubernetes/kubelet.conf
      alias k=kubectl
  #    complete -o default -F __start_kubectl k 
  #  copy: 
  #    src: '/etc/kubernetes/admin.conf'
  #    dest: '/root/.kube/config.yaml'
  #    remote_src: yes
  tags:
    - k8s_connect

- name: source bashrc
  shell: . /root/.bashrc
  tags:
    - k8s_connect

