- name: rke-init
  hosts: master
  remote_user: root
  tasks:
  - name: making config.yaml
    file:
      path: "/etc/rancher/rke2/config.yaml"
      state: touch
  - name: append content
    blockinfile:
      path: "/etc/rancher/rke2/config.yaml"
      block: |
        node-ip: 192.168.31.161
        cni: "calico"
        tls-san:
          - my-kubernetes-domain.com
          - another-kubernetes-domain.com
  - name: rke-master-up
    shell: systemctl start rke2-server.service
  - name: get token
    shell: cat /var/lib/rancher/rke2/server/node-token
    register: TOKEN
  - name: making another config.yaml
    file:
      path: "./config.yaml"
      state: touch
  - name: append token content
    blockinfile:
      path: "./config.yaml"
      block: |
        token: {{ TOKEN.stdout }}
        server: https://192.168.31.161:9345
        cni: "calico"
        tls-san:
          - my-kubernetes-domain.com
          - another-kubernetes-domain.com
  - name: fetching config.yaml
    fetch:
      src: "./config.yaml"
      dest: "./config.yaml"
      flat: yes
  - name: get kubeconfig
    fetch:
      src: "/etc/rancher/rke2/rke2.yaml"
      dest: "/root/.kube/config"
      flat: yes

- name: rke2-worker-up
  hosts: worker
  remote_user: root
  tasks:
  - name: send config.yaml
    copy:
      src: "./config.yaml"
      dest: "/etc/rancher/rke2/config.yaml"
  - name: rke2-worker-init
    systemd: 
      name: rke2-agent
      state: started

- name: rke2-container-runtime-set
  hosts: rke2-cluster
  remote_user: root
  tasks:
  - name: set-runtime
    lineinfile:
      path: ~/.bashrc
      line: "export CRI_CONFIG_FILE=/var/lib/rancher/rke2/agent/etc/crictl.yaml"
  - name: set-CRI_CONFIG
    shell: export CRI_CONFIG_FILE=/var/lib/rancher/rke2/agent/etc/crictl.yaml

- name: rke2-component-up
  hosts: localhost
  tasks:
  - name: edit kubeconfig
    shell: "sed -i -e 's,server:.*,server: https://192.168.31.161:6443,' /root/.kube/config"
  - name: certmanager apply
    shell: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.12.6/cert-manager.yaml
  - name: certmanager rollout 1
    shell: kubectl -n cert-manager rollout status deploy/cert-manager
  - name: certmanager rollout 2
    shell: kubectl -n cert-manager rollout status deploy/cert-manager-webhook 
  - name: install helm
    shell: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  - name: helm repo add rancher-stable   
    shell: helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
  - name: helm install rancher-stable
    shell: helm install rancher rancher-stable/rancher --create-namespace --namespace cattle-system --set hostname=192.168.31.161.nip.io --set replicas=2 --set bootstrapPassword="new1234!" --set global.cattle.psp.enabled=false